---
# - hosts: all
# - import_playbook: ../static-assignments/common.yml

#- hosts: all
#- name: Include dynamic variables
#  tasks:
#  import_playbook: ../static-assignments/common.yml
#  include: ../dynamic-assignments/env-vars.yml
#  tags:
#    - always
#
#- hosts: uat-webservers
#- import_playbook: ../static-assignments/uat-webservers.yml
#
- name: import common file
  import_playbook: ../static-assignments/common.yml
  tags:
    - always

- name: include env-vars files
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: import database file
  import_playbook: ../static-assignments/database.yml

- name: import webservers file
  import_playbook: ../static-assignments/webservers.yml

- name: import loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required

